Imagenet10 tar 2
SeldonIO/alibi pull request #713
Opened 2022-07-06 14:20 UTC by gipster

* Addresses issue https://github.com/SeldonIO/alibi/issues/687 .

* Changed storage file format from joblib to tar.gz

notes:
In order to load .npy files from a tar archive, the changed function uses the method described https://github.com/numpy/numpy/issues/7989#issuecomment-340921579.

2022-07-20 13:35 UTC, jklaise commented on alibi/datasets/default.py
>  def fetch_imagenet_10(url_id: int = 0) -> Dict:
Please add a docstring for `url_id`, i.e. `Index specifying which URL to use for downloading`

2022-07-20 13:37 UTC, jklaise commented on alibi/datasets/default.py
> +    int_to_str_labels = json.load(tar.extractfile('imagenet10/int_to_str_labels.json'))  # type: ignore
Can you narrow down the `type: ignore` statements using the error codes shown please? I.e. `type: ignore[error-code]`.

2022-07-20 13:40 UTC, jklaise commented on alibi/datasets/default.py
> +    imagenet10 = {}
I would move this to bottom where the return dictionary is created for clarity. Or consider even building it in one go, i.e.
```python
imagenet10 = {
    'trainset': (X_train, y_train),
    ...
}
```

2022-07-20 13:40 UTC, jklaise requested changes
Thanks Giovanni, couple of minor comments but looks good.

2022-08-22 15:30 UTC, gipster commented
Hey, just pushed the new version with the changes requested.

2022-08-23 12:48 UTC, jklaise commented on alibi/datasets/default.py
> +    url_id: Index specifying which URL to use for downloading.
This is not the `numpy` docstring format, description should be on a new line with an indent and no colon. If in doubt, recreate a new docstring which will auto-format (assuming Pycharm is set up with the `numpy` style docstrings) with all the parameters included.

2022-08-23 12:49 UTC, jklaise approved these changes
Thanks, just the docstring format needs to be fixed to follow `numpy` docstring conventions and then good to merge.

2022-08-24 11:06 UTC, merged